app:
  security:
    user: api
    password: ${API_PASSWORD:pismo123}  # override with env var in prod
spring:
  jackson:
    property-naming-strategy: SNAKE_CASE
    serialization:
      write-dates-as-timestamps: false
  datasource:
    url: jdbc:h2:mem:pismo;DB_CLOSE_DELAY=-1;MODE=PostgreSQL
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate.format_sql: true
  h2:
    console:
      enabled: true
      path: /h2-console

server:
  port: 8080
